Added solution
AndreiYazadzhi/multithreading pull request #1
Opened 2021-02-22 15:30 UTC by AndreiYazadzhi

2021-02-22 22:06 UTC, Ketch92 requested changes

2021-02-22 22:06 UTC, Ketch92 commented on src/main/java/Main.java
> +        new Thread(runnableExample).start();
you can wrap it 
```suggestion
        new Thread(new MyRunnable()).start();
```

2021-02-22 22:07 UTC, Ketch92 requested changes
Тобі потрібно, щоб два потоки кокурували за доступ до одного ресурсу. Завдання не передбачає каунтер у кожному потоці. У тебе має бути один каутер який ти передаватимеш у два конструктори потоків.

2021-02-23 08:47 UTC, Ketch92 approved these changes

2021-02-23 09:59 UTC, Sofasmile approved these changes

2021-02-23 09:59 UTC, Sofasmile commented on src/main/java/MyRunnable.java
> +        this.index = index;
```suggestion
    private final Counter counter;

    public MyRunnable(Counter counter) {
        this.counter = counter;
```

2021-02-23 19:30 UTC, merged