hw-2
AndreiYazadzhi/multithreading pull request #2
Opened 2021-02-23 19:28 UTC by AndreiYazadzhi

2021-02-23 20:00 UTC, Fedich09 requested changes

2021-02-23 20:00 UTC, mfedenko09 commented on pom.xml
> +</project>
```suggestion
</project>

```

2021-02-23 20:11 UTC, Fedich09 approved these changes

2021-02-24 11:37 UTC, RomanDubovskyi requested changes

2021-02-24 11:37 UTC, RomanDubovskyi commented on log/thread.log
> + 10:07:26,242 INFO  MyThread:16 - Thread-1: 97
this file shouldn't be in PR

2021-02-24 11:37 UTC, RomanDubovskyi commented on pom.xml
> +</project>
empty line at the end of the file

2021-02-24 11:37 UTC, RomanDubovskyi commented on src/main/java/Counter.java
> +public class Counter {
same here

2021-02-24 11:37 UTC, RomanDubovskyi commented on src/main/java/MyCallable.java
> +        ExecutorService executor = Executors.newFixedThreadPool(threads);
separate this logic into 2 different classes. First is callable impl that performs some atomic task. Second class will manage ExecutorService and use Callable impls inside

2021-02-24 11:37 UTC, RomanDubovskyi commented on src/main/java/MyRecursive.java
> +public class MyRecursive extends RecursiveTask<Integer> {
name classes according to their purpose

2021-02-24 11:37 UTC, RomanDubovskyi commented on src/test/java/CalculationTest.java
> +public class CalculationTest {
you should have separate class per each class that you're testing

2021-02-24 15:54 UTC, closed without merging